# Generated by Django 5.2.1 on 2025-05-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("public_date", models.DateTimeField(auto_now_add=True)),
                ("image", models.ImageField(upload_to="images/")),
                ("body", models.TextField(max_length=10000)),
            ],
        ),
        migrations.AlterField(
            model_name="contact",
            name="content",
            field=models.TextField(max_length=10000),
        ),
    ]
